# Generated by Django 5.0.6 on 2024-07-20 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoapp', '0002_package_user_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='mydjangoapp.user'),
        ),
        migrations.AddField(
            model_name='package',
            name='courier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prik',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pubk',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pymnt',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_deliveries', to='mydjangoapp.user'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier_deliveries', to='mydjangoapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
